-- Add La Sola Sunset Bar & Lounge as a curated Catangnan venue beside AFAM Bridge.

INSERT INTO "Venue" (
  "id",
  "slug",
  "name",
  "description",
  "address",
  "city",
  "country",
  "latitude",
  "longitude",
  "geohash",
  "timezone",
  "categories",
  "status",
  "isPartner",
  "partnerTier",
  "placeSource",
  "externalPlaceId",
  "checkInRadiusMeters",
  "metadataJson",
  "createdAt",
  "updatedAt"
)
VALUES (
  'seed_la_sola_sunset_bar_and_lounge',
  'la-sola-sunset-bar-and-lounge',
  'La Sola Sunset Bar & Lounge',
  'Sunset bar and lounge beside Catangnan (AFAM) Bridge for golden-hour drinks and easy social discovery.',
  'R554+RC8, General Luna, Surigao del Norte, Philippines',
  'General Luna',
  'Philippines',
  9.8098397,
  126.1560223,
  'wc9xyc',
  'Asia/Manila',
  ARRAY['bar', 'lounge', 'sunset', 'cocktails', 'nightlife', 'social', 'catangnan', 'siargao', 'general-luna']::TEXT[],
  'ACTIVE',
  false,
  NULL,
  'BASEDARE_CURATED',
  'curated:la-sola-sunset-bar-and-lounge',
  120,
  jsonb_build_object(
    'curated', true,
    'curatedSet', 'siargao-v6',
    'featuredLabel', 'unmarked',
    'vibe', 'Sunset bar and lounge beside Catangnan (AFAM) Bridge for golden-hour drinks and easy social discovery.',
    'locationConfidence', 'externally-checked-anchor',
    'coordinatePolicy', 'Pinned to the current public map listing beside Catangnan (AFAM) Bridge.',
    'instagramHandle', '@lasola.siargao'
  ),
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("slug") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "address" = EXCLUDED."address",
  "city" = EXCLUDED."city",
  "country" = EXCLUDED."country",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "geohash" = EXCLUDED."geohash",
  "timezone" = EXCLUDED."timezone",
  "categories" = EXCLUDED."categories",
  "status" = EXCLUDED."status",
  "placeSource" = EXCLUDED."placeSource",
  "externalPlaceId" = EXCLUDED."externalPlaceId",
  "checkInRadiusMeters" = EXCLUDED."checkInRadiusMeters",
  "metadataJson" = COALESCE("Venue"."metadataJson", '{}'::jsonb) || EXCLUDED."metadataJson",
  "updatedAt" = CURRENT_TIMESTAMP;
