-- Add more seeded Siargao venue anchors so the General Luna map does not feel empty.

WITH siargao_venues(
  id,
  slug,
  name,
  description,
  address,
  city,
  country,
  latitude,
  longitude,
  geohash,
  categories,
  featured_label,
  location_confidence
) AS (
  VALUES
    (
      'seed_shaka_siargao',
      'shaka-siargao',
      'Shaka Siargao',
      'Cloud 9 smoothie-bowl and surf-view stop that gives the Catangnan side a daytime proof anchor.',
      'Tourism Road, Cloud 9',
      'General Luna',
      'Philippines',
      9.81255::double precision,
      126.15965::double precision,
      'wc9xyf',
      ARRAY['cafe', 'healthy', 'surf-view', 'cloud-9', 'siargao']::TEXT[],
      'active',
      'approximate-seed'
    ),
    (
      'seed_kermit_siargao',
      'kermit-siargao',
      'Kermit Siargao',
      'Surf-camp restaurant node between town and Cloud 9 for dinner marks, surf plans, and creator meetups.',
      'Purok 5',
      'General Luna',
      'Philippines',
      9.79895::double precision,
      126.1582::double precision,
      'wc9xwz',
      ARRAY['restaurant', 'surf-camp', 'pizza', 'social', 'siargao']::TEXT[],
      'hot',
      'approximate-seed'
    ),
    (
      'seed_bravo_restaurant_siargao',
      'bravo-restaurant-siargao',
      'Bravo Restaurant Siargao',
      'Beachfront General Luna dinner and drinks anchor with lagoon-facing social energy.',
      'Tourism Road, Barangay 5',
      'General Luna',
      'Philippines',
      9.79315::double precision,
      126.1609::double precision,
      'wc9xwy',
      ARRAY['restaurant', 'beachfront', 'bar', 'dinner', 'siargao']::TEXT[],
      'active',
      'approximate-seed'
    ),
    (
      'seed_harana_surf_resort',
      'harana-surf-resort',
      'Harana Surf Resort',
      'Tuason/Catangnan surf-resort stop for surf lessons, food, and after-session place memory.',
      'Tuason Point, Barangay Catangnan',
      'General Luna',
      'Philippines',
      9.80795::double precision,
      126.16125::double precision,
      'wc9xyc',
      ARRAY['surf', 'resort', 'restaurant', 'catangnan', 'siargao']::TEXT[],
      'simmering',
      'approximate-seed'
    ),
    (
      'seed_white_beard_coffee_siargao',
      'white-beard-coffee-siargao',
      'White Beard Coffee Siargao',
      'Poblacion coffee and breakfast stop that fills the town-side morning route.',
      'Poblacion 1',
      'General Luna',
      'Philippines',
      9.7909::double precision,
      126.15855::double precision,
      'wc9xwy',
      ARRAY['coffee', 'breakfast', 'cafe', 'poblacion', 'siargao']::TEXT[],
      'active',
      'approximate-seed'
    ),
    (
      'seed_las_barricas_siargao',
      'las-barricas-siargao',
      'Las Barricas Siargao',
      'Spanish and taco dinner spot in General Luna that adds a compact food-nightlife pin.',
      'Poblacion V, General Luna',
      'General Luna',
      'Philippines',
      9.7897::double precision,
      126.16055::double precision,
      'wc9xwy',
      ARRAY['restaurant', 'tapas', 'tacos', 'dinner', 'siargao']::TEXT[],
      'simmering',
      'approximate-seed'
    ),
    (
      'seed_barrel_siargao',
      'barrel-siargao',
      'BARREL Siargao',
      'Beachfront sports-bar anchor for late food, games, and nightlife marks near the main General Luna strip.',
      'Route to Romantic',
      'General Luna',
      'Philippines',
      9.7898::double precision,
      126.1621::double precision,
      'wc9xwy',
      ARRAY['sports-bar', 'beachfront', 'nightlife', 'food', 'siargao']::TEXT[],
      'hot',
      'approximate-seed'
    ),
    (
      'seed_general_luna_island_hopping_dock',
      'general-luna-island-hopping-dock',
      'General Luna Island Hopping Dock',
      'Public launch point for tri-island tours, boat meetups, and high-intent tourist movement.',
      'General Luna Local Market',
      'General Luna',
      'Philippines',
      9.78115::double precision,
      126.15645::double precision,
      'wc9xwu',
      ARRAY['dock', 'island-hopping', 'tourism', 'boats', 'siargao']::TEXT[],
      'first-spark',
      'landmark-approximate'
    ),
    (
      'seed_tuason_point',
      'tuason-point',
      'Tuason Point',
      'Advanced surf-break pin north of General Luna that stretches the map past Cloud 9.',
      'Tuason Point, Catangnan',
      'General Luna',
      'Philippines',
      9.8041::double precision,
      126.16555::double precision,
      'wc9xyb',
      ARRAY['surf', 'reef-break', 'catangnan', 'advanced', 'siargao']::TEXT[],
      'first-spark',
      'landmark-approximate'
    ),
    (
      'seed_malinao_beach',
      'malinao-beach',
      'Malinao Beach',
      'Quieter beach-side General Luna anchor so the map has a calmer south-side route too.',
      'Malinao Road',
      'General Luna',
      'Philippines',
      9.7618::double precision,
      126.14565::double precision,
      'wc9xw9',
      ARRAY['beach', 'quiet', 'malinao', 'tourism', 'siargao']::TEXT[],
      'unmarked',
      'landmark-approximate'
    )
)
INSERT INTO "Venue" (
  "id",
  "slug",
  "name",
  "description",
  "address",
  "city",
  "country",
  "latitude",
  "longitude",
  "geohash",
  "timezone",
  "categories",
  "status",
  "isPartner",
  "partnerTier",
  "placeSource",
  "externalPlaceId",
  "metadataJson",
  "createdAt",
  "updatedAt"
)
SELECT
  id,
  slug,
  name,
  description,
  address,
  city,
  country,
  latitude,
  longitude,
  geohash,
  'Asia/Manila',
  categories,
  'ACTIVE',
  false,
  NULL,
  'seed',
  'seed:' || slug,
  jsonb_build_object(
    'seeded', true,
    'seedBatch', 'siargao-density-20260512',
    'featuredLabel', featured_label,
    'vibe', description,
    'locationConfidence', location_confidence
  ),
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM siargao_venues
ON CONFLICT ("slug") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "address" = EXCLUDED."address",
  "city" = EXCLUDED."city",
  "country" = EXCLUDED."country",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "geohash" = EXCLUDED."geohash",
  "timezone" = EXCLUDED."timezone",
  "categories" = EXCLUDED."categories",
  "status" = EXCLUDED."status",
  "placeSource" = EXCLUDED."placeSource",
  "externalPlaceId" = EXCLUDED."externalPlaceId",
  "metadataJson" = COALESCE("Venue"."metadataJson", '{}'::jsonb) || EXCLUDED."metadataJson",
  "updatedAt" = CURRENT_TIMESTAMP;

UPDATE "Venue"
SET
  "latitude" = 9.81276::double precision,
  "longitude" = 126.16408::double precision,
  "geohash" = 'wc9xyf',
  "metadataJson" = COALESCE("metadataJson", '{}'::jsonb) || jsonb_build_object(
    'locationConfidence', 'plus-code-corrected',
    'coordinatePolicy', 'Pinned near the Cloud 9 boardwalk entrance instead of the west-side water label.'
  ),
  "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" = 'cloud-9-boardwalk';
