ALTER TABLE "StreamerTag"
ADD COLUMN "pfpScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "pfpOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "pfpOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 50;
