import 'server-only';

import { prisma } from '@/lib/prisma';
import { calculateDistance, encodeGeohash } from '@/lib/geo';

type CuratedVenue = {
  slug: string;
  name: string;
  description: string;
  address: string;
  city: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
  categories: string[];
  locationConfidence?: string;
  instagramHandle?: string;
};

export const CURATED_SIARGAO_VENUES: CuratedVenue[] = [
  {
    slug: 'hideaway',
    name: 'Hideaway',
    description:
      'Boardwalk bar energy right by the island hopping dock in General Luna.',
    address: 'Boardwalk, General Luna, 8419 Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7810522,
    longitude: 126.1570569,
    timezone: 'Asia/Manila',
    categories: ['nightlife', 'boardwalk', 'dock', 'bar', 'dinner', 'late-night', 'siargao', 'general-luna'],
  },
  {
    slug: 'siargao-beach-club',
    name: 'Siargao Beach Club',
    description:
      'Nightlife and beach-club pilot venue for BaseDare venue-memory and QR-console testing in General Luna.',
    address: 'Tourism Road, Purok 3, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.785133,
    longitude: 126.161438,
    timezone: 'Asia/Manila',
    categories: ['nightlife', 'music', 'beach-club', 'bar', 'dinner', 'late-night', 'siargao', 'general-luna'],
  },
  {
    slug: 'cloud-9-boardwalk',
    name: 'Cloud 9 Boardwalk',
    description:
      'Iconic surf-side walkway and a clean first-mark target for Siargao.',
    address: 'Cloud 9, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.81276,
    longitude: 126.16408,
    timezone: 'Asia/Manila',
    categories: ['surf', 'boardwalk', 'iconic', 'beach', 'sunrise', 'morning', 'siargao', 'catangnan'],
  },
  {
    slug: 'the-cat-and-gun',
    name: 'The Cat & Gun',
    description:
      'Catangnan coffee and sports-bar stop with a clean creator rail for food, match-night, and island hangout dares.',
    address: 'Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8093625,
    longitude: 126.1598594,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'coffee',
      'breakfast',
      'brunch',
      'lunch',
      'sports-bar',
      'food',
      'work-friendly',
      'siargao',
      'catangnan',
    ],
  },
  {
    slug: 'la-sola-sunset-bar-and-lounge',
    name: 'La Sola Sunset Bar & Lounge',
    description:
      'Sunset bar and lounge beside Catangnan (AFAM) Bridge for golden-hour drinks and easy social discovery.',
    address: 'R554+RC8, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8098397,
    longitude: 126.1560223,
    timezone: 'Asia/Manila',
    instagramHandle: '@lasola.siargao',
    categories: [
      'bar',
      'lounge',
      'sunset',
      'cocktails',
      'nightlife',
      'social',
      'catangnan',
      'siargao',
      'general-luna',
    ],
  },
  {
    slug: 'shaka-siargao',
    name: 'Shaka Siargao',
    description:
      'Cloud 9 smoothie-bowl and surf-view stop that gives the Catangnan side a daytime proof anchor.',
    address: 'Tourism Road, Cloud 9, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8119606,
    longitude: 126.1644192,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'coffee',
      'breakfast',
      'brunch',
      'smoothie-bowl',
      'healthy',
      'surf-view',
      'morning',
      'cloud-9',
      'siargao',
      'catangnan',
    ],
  },
  {
    slug: 'kermit-siargao',
    name: 'Kermit Siargao',
    description:
      'Surf-camp restaurant node between town and Cloud 9 for dinner marks, surf plans, and creator meetups.',
    address: 'Purok 5, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7877583,
    longitude: 126.160523,
    timezone: 'Asia/Manila',
    categories: ['restaurant', 'surf-camp', 'pizza', 'lunch', 'dinner', 'social', 'siargao', 'general-luna'],
  },
  {
    slug: 'primefit-gym-general-luna',
    name: 'PrimeFit Gym General Luna',
    description:
      'General Luna strength and conditioning gym with weights, cardio equipment, functional training, and a stretching area.',
    address: 'Tourism Road, Purok 3, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7854365,
    longitude: 126.1604944,
    timezone: 'Asia/Manila',
    categories: [
      'fitness',
      'gym',
      'weight-training',
      'strength',
      'cardio',
      'functional-fitness',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'surfit-gym-siargao',
    name: 'SurFit Gym Siargao',
    description:
      'Tourism Road training and recovery gym with strength equipment, cardio, infrared sauna, and ice baths.',
    address: 'Tourism Road, Purok 5, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.787995,
    longitude: 126.1630469,
    timezone: 'Asia/Manila',
    categories: [
      'fitness',
      'gym',
      'strength',
      'weight-training',
      'cardio',
      'sauna',
      'ice-bath',
      'recovery',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'fat-lips-surfshop',
    name: 'Fat Lips Surfshop',
    description:
      'Long-running General Luna surf shop with a large rental-board selection, surf hardware, and board-rack motorbikes.',
    address: 'Tourism Road, Purok 5, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7918636,
    longitude: 126.161416,
    timezone: 'Asia/Manila',
    instagramHandle: '@fatlips_surfco',
    categories: [
      'surf-rental',
      'surf-shop',
      'board-rental',
      'surf-gear',
      'motorbike-rental',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'marco-surf-school-siargao',
    name: 'Marco Surf School Siargao',
    description:
      'Jacking Horse surf school for private and group lessons, local coaching, and board-inclusive sessions.',
    address: 'Barangay Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.812601,
    longitude: 126.1620351,
    timezone: 'Asia/Manila',
    instagramHandle: '@marcosurfschoolsiargao',
    categories: [
      'surf-school',
      'surf-rental',
      'board-rental',
      'surf-lessons',
      'surf-coaching',
      'jacking-horse',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'kanaway-surf-school',
    name: 'Kanaway Surf School',
    description:
      'Catangnan surf school for lessons, local guiding, and board access near the Cloud 9 surf zone.',
    address: 'Barangay Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8108572,
    longitude: 126.159073,
    timezone: 'Asia/Manila',
    categories: [
      'surf-school',
      'surf-rental',
      'board-rental',
      'surf-lessons',
      'surf-guiding',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'bravo-restaurant-siargao',
    name: 'Bravo Restaurant Siargao',
    description:
      'Beachfront General Luna dinner and drinks anchor with lagoon-facing social energy.',
    address: 'Tourism Road, Barangay 5, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7919,
    longitude: 126.162584,
    timezone: 'Asia/Manila',
    categories: ['restaurant', 'beachfront', 'bar', 'breakfast', 'brunch', 'dinner', 'siargao', 'general-luna'],
  },
  {
    slug: 'harana-surf-resort',
    name: 'Harana Surf Resort',
    description:
      'Tuason/Catangnan surf-resort stop for surf lessons, food, and after-session place memory.',
    address: 'Tuason Point, Barangay Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8068136,
    longitude: 126.1670614,
    timezone: 'Asia/Manila',
    categories: ['surf', 'resort', 'restaurant', 'breakfast', 'lunch', 'catangnan', 'siargao', 'tuason'],
  },
  {
    slug: 'white-beard-coffee-siargao',
    name: 'White Beard Coffee Siargao',
    description:
      'Poblacion coffee and breakfast stop that fills the town-side morning route.',
    address: 'Poblacion 1, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7820115,
    longitude: 126.1560357,
    timezone: 'Asia/Manila',
    categories: [
      'coffee',
      'breakfast',
      'brunch',
      'cafe',
      'morning',
      'work-friendly',
      'poblacion',
      'siargao',
      'general-luna',
    ],
  },
  {
    slug: 'mr-turtle-siargao',
    name: 'Mr. Turtle Siargao',
    description:
      'Catangnan beachfront breakfast, smoothie, and social anchor near Goodcoast for morning proof loops.',
    address: 'Goodcoast, Tourism Road, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.80695,
    longitude: 126.1662,
    timezone: 'Asia/Manila',
    locationConfidence: 'approximate-goodcoast-anchor',
    categories: [
      'restaurant',
      'breakfast',
      'brunch',
      'smoothie',
      'wellness',
      'beachfront',
      'bar',
      'catangnan',
      'trendy',
      'siargao',
    ],
  },
  {
    slug: 'greenhouse-cafe-siargao',
    name: 'Greenhouse Cafe Siargao',
    description:
      'Laidback Tourism Road breakfast cafe with organic island food and a calm morning route near Reef Beach.',
    address: 'Greenhouse, Tourism Road, General Luna, Siargao, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.803789,
    longitude: 126.161223,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'breakfast',
      'brunch',
      'healthy',
      'organic',
      'coffee',
      'morning',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'green-waves-cafe-siargao',
    name: 'Green Waves Cafe',
    description:
      'Purok 3 cafe for coffee, brunch, smoothie bowls, and late casual food on the General Luna strip.',
    address: 'Purok 3 Tourism Road, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7843233,
    longitude: 126.1580796,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'coffee',
      'breakfast',
      'brunch',
      'smoothie-bowl',
      'dessert',
      'work-friendly',
      'late-night',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'spotted-pig-cafe-siargao',
    name: 'Spotted Pig Cafe',
    description:
      'Catangnan all-day breakfast and specialty coffee stop with a strong brunch/work-friendly signal.',
    address: 'Tourism Road, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.80199,
    longitude: 126.15996,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'coffee',
      'breakfast',
      'brunch',
      'bakery',
      'work-friendly',
      'catangnan',
      'trendy',
      'siargao',
    ],
  },
  {
    slug: 'tawhay-fitness-siargao',
    name: 'Tawhay Fitness Siargao',
    description:
      'Social wellness club with a gym, Pilates and yoga classes, functional training, sauna, cold plunge, and recovery space.',
    address: 'Old Tourism Road, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8020661,
    longitude: 126.1582323,
    timezone: 'Asia/Manila',
    instagramHandle: '@tawhaysiargao',
    categories: [
      'fitness',
      'gym',
      'pilates',
      'yoga',
      'functional-fitness',
      'sauna',
      'cold-plunge',
      'recovery',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'padel-and-palms-siargao',
    name: 'Padel & Palms',
    description:
      'Back Road padel club with four courts for an easy social game away from the nightlife strip.',
    address: 'The Back Road, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8022751,
    longitude: 126.1587293,
    timezone: 'Asia/Manila',
    categories: [
      'fitness',
      'padel',
      'sports-court',
      'racket-sport',
      'social-sport',
      'catangnan',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'shapeshifter-cafe-siargao',
    name: 'Shapeshifter Cafe',
    description:
      'Back Road cafe beside Tropical Temple for breakfast, smoothie bowls, surf errands, and quiet work starts.',
    address: 'St. Ines Back Road, next to Tropical Temple, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8010026,
    longitude: 126.1582172,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'breakfast',
      'brunch',
      'smoothie-bowl',
      'coffee',
      'work-friendly',
      'surf',
      'back-road',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'goodies-siargao',
    name: 'Goodies Siargao',
    description:
      'Healthy cafe, restaurant, bar, and eco shop on Tourism Road for breakfast, smoothies, and all-day food.',
    address: 'Arka Hayahay Surf and Beach Resort, Tourism Road, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8019569,
    longitude: 126.1599488,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'restaurant',
      'bar',
      'breakfast',
      'brunch',
      'healthy',
      'smoothie',
      'eco-shop',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'happiness-beach-bar-siargao',
    name: 'Happiness Beach Bar Siargao',
    description:
      'Catangnan beach bar and social hostel stop for Sunday sessions, poolside hangs, and meeting other travellers.',
    address: 'Tourism Road, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8018102,
    longitude: 126.159654,
    timezone: 'Asia/Manila',
    categories: [
      'bar',
      'nightlife',
      'social',
      'hostel',
      'pool',
      'sunday',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'naga-siargao',
    name: 'NAGA Siargao',
    description:
      'Tourism Road restaurant, cocktail bar, and work-friendly social stop for daytime laptop sessions and dinner.',
    address: 'Tourism Road, General Luna, Siargao Island, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.79235,
    longitude: 126.16008,
    timezone: 'Asia/Manila',
    categories: [
      'restaurant',
      'bar',
      'cocktails',
      'coffee',
      'work-friendly',
      'lunch',
      'dinner',
      'nightlife',
      'trendy',
      'siargao',
    ],
  },
  {
    slug: 'gaya-rooftop-space',
    name: 'GAYA Rooftop Space',
    description:
      'Lexias rooftop social venue for sunset sessions, brunch energy, coworking spillover, and night events.',
    address: 'Lexias Hostel and Workspace, General Luna, Siargao, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.80335,
    longitude: 126.15685,
    timezone: 'Asia/Manila',
    categories: [
      'rooftop',
      'restaurant',
      'bar',
      'brunch',
      'sunset',
      'nightlife',
      'coworking',
      'events',
      'trendy',
      'siargao',
    ],
  },
  {
    slug: 'loka-siargao',
    name: 'LOKA Siargao',
    description:
      'Cloud 9 beachfront restaurant, bar, and shop with early coffee, breakfast, surf fuel, and sunset food.',
    address: 'Cloud 9 Drive, General Luna, Siargao Island, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8132877,
    longitude: 126.1632141,
    timezone: 'Asia/Manila',
    categories: [
      'restaurant',
      'bar',
      'coffee',
      'breakfast',
      'brunch',
      'beachfront',
      'surf-view',
      'cloud-9',
      'trendy',
      'siargao',
    ],
  },
  {
    slug: 'vultun-jacking-horse-siargao',
    name: 'Vultun Siargao',
    description:
      'Jacking Horse wellness stop for massage and bodywork, with surf coaching and board rental available from the same beach hub.',
    address: 'Jacking Horse Beach, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8129708,
    longitude: 126.1615121,
    timezone: 'Asia/Manila',
    instagramHandle: '@vultun_siargao',
    categories: [
      'wellness',
      'massage',
      'spa',
      'recovery',
      'surf-school',
      'surf-rental',
      'jacking-horse',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'buddha-wellness-siargao',
    name: 'Buddha Wellness Siargao',
    description:
      'Buddha Resort wellness hub for yoga, Pilates, ice baths, private classes, and restorative island sessions.',
    address: 'Buddha Resort, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7965975,
    longitude: 126.1597235,
    timezone: 'Asia/Manila',
    categories: [
      'wellness',
      'yoga',
      'pilates',
      'ice-bath',
      'recovery',
      'private-class',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'mujo-ice-bath-siargao',
    name: 'MUJŌ Ice Bath Siargao',
    description:
      'Tourism Road cold-therapy and recovery stop pairing guided ice baths with a small island juicery.',
    address: 'Tourism Road, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7897725,
    longitude: 126.1620035,
    timezone: 'Asia/Manila',
    categories: [
      'wellness',
      'ice-bath',
      'cold-plunge',
      'recovery',
      'juice',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'filosofia-wellness-siargao',
    name: 'Filosofía Wellness Siargao',
    description:
      'Catangnan wellness studio for massage, bodywork, recovery, and slower restorative sessions.',
    address: 'Old Tourism Road, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8061726,
    longitude: 126.1602151,
    timezone: 'Asia/Manila',
    categories: [
      'wellness',
      'massage',
      'spa',
      'bodywork',
      'recovery',
      'catangnan',
      'general-luna',
      'siargao',
    ],
  },
  {
    slug: 'nalu-cafe-bistro-siargao',
    name: 'Nalu Cafe Bistro Siargao',
    description:
      'Back Road Saging-saging bistro for Catangnan breakfast, coffee, and calmer inland food discovery.',
    address: 'Back Road Saging-saging, Barangay Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8068,
    longitude: 126.1544,
    timezone: 'Asia/Manila',
    categories: [
      'cafe',
      'bistro',
      'breakfast',
      'brunch',
      'coffee',
      'back-road',
      'catangnan',
      'siargao',
    ],
  },
  {
    slug: 'las-barricas-siargao',
    name: 'Las Barricas Siargao',
    description:
      'Spanish and taco dinner spot in General Luna that adds a compact food-nightlife pin.',
    address: 'Poblacion V, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7897,
    longitude: 126.16055,
    timezone: 'Asia/Manila',
    categories: ['restaurant', 'tapas', 'tacos', 'dinner', 'late-night', 'siargao', 'general-luna'],
  },
  {
    slug: 'barrel-siargao',
    name: 'BARREL Siargao',
    description:
      'Beachfront sports-bar anchor for late food, games, and nightlife marks near the main General Luna strip.',
    address: 'Route to Romantic, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7896886,
    longitude: 126.161981,
    timezone: 'Asia/Manila',
    categories: ['sports-bar', 'beachfront', 'nightlife', 'food', 'dinner', 'late-night', 'siargao', 'general-luna'],
  },
  {
    slug: 'barbosa-siargao',
    name: 'Barbosa Siargao',
    description:
      'Purok 3 pub and music-led nightlife stop beside Barrel for cocktails, food, vinyl energy, and late social discovery.',
    address: 'Tourism Road, Poblacion III, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.789532,
    longitude: 126.161923,
    timezone: 'Asia/Manila',
    instagramHandle: '@barbosasiargao',
    categories: [
      'pub',
      'bar',
      'nightlife',
      'music',
      'cocktails',
      'food',
      'late-night',
      'purok-3',
      'siargao',
      'general-luna',
    ],
  },
  {
    slug: 'general-luna-island-hopping-dock',
    name: 'General Luna Island Hopping Dock',
    description:
      'Public launch point for tri-island tours, boat meetups, and high-intent tourist movement.',
    address: 'General Luna Local Market, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.78115,
    longitude: 126.15645,
    timezone: 'Asia/Manila',
    categories: ['dock', 'island-hopping', 'tourism', 'boats', 'morning', 'siargao', 'general-luna'],
  },
  {
    slug: 'tuason-point',
    name: 'Tuason Point',
    description:
      'Advanced surf-break pin north of General Luna that stretches the map past Cloud 9.',
    address: 'Tuason Point, Catangnan, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.8094,
    longitude: 126.1683,
    timezone: 'Asia/Manila',
    categories: ['surf', 'reef-break', 'sunrise', 'morning', 'catangnan', 'advanced', 'siargao', 'tuason'],
  },
  {
    slug: 'malinao-beach',
    name: 'Malinao Beach',
    description:
      'Quieter beach-side General Luna anchor so the map has a calmer south-side route too.',
    address: 'Malinao Road, General Luna, Surigao del Norte, Philippines',
    city: 'General Luna',
    country: 'Philippines',
    latitude: 9.7684925,
    longitude: 126.1289878,
    timezone: 'Asia/Manila',
    categories: ['beach', 'quiet', 'sunset', 'malinao', 'tourism', 'siargao', 'general-luna'],
  },
];

const SIARGAO_QUERY_TOKENS = [
  'cat',
  'gun',
  'la sola',
  'afam bridge',
  'catangnan',
  'siargao',
  'general luna',
  'surigao',
  'hideaway',
  'cloud 9',
  'beach club',
  'shaka',
  'kermit',
  'primefit',
  'prime fit',
  'surfit',
  'sur fit',
  'marco surf',
  'kanaway',
  'surf school',
  'fat lips',
  'surf rental',
  'surfboard',
  'board rental',
  'surf shop',
  'foil',
  'wing foil',
  'wingfoil',
  'kite',
  'paddleboard',
  'kayak',
  'bravo',
  'harana',
  'white beard',
  'mr turtle',
  'mr. turtle',
  'mr.turtle',
  'goodcoast',
  'good coast',
  'greenhouse',
  'green waves',
  'spotted pig',
  'tawhay',
  'pilates',
  'gym',
  'fitness',
  'weights',
  'sauna',
  'cold plunge',
  'recovery',
  'padel',
  'tennis',
  'racket',
  'shapeshifter',
  'tropical temple',
  'st ines',
  'goodies',
  'happiness',
  'naga',
  'gaya',
  'lexias',
  'loka',
  'vultun',
  'buddha wellness',
  'buddha resort',
  'mujo',
  'mujō',
  'ice bath',
  'filosofia',
  'filosofía',
  'massage',
  'spa',
  'wellness',
  'nalu',
  'back road',
  'saging',
  'purok 3',
  'las barricas',
  'barrel',
  'barbosa',
  'island hopping',
  'tuason',
  'malinao',
  'breakfast',
  'brunch',
  'coffee',
  'cafe',
  'smoothie',
  'smoothie bowl',
  'bakery',
  'healthy',
  'vegan',
  'wifi',
  'work',
  'laptop',
  'rooftop',
  'trendy',
  'morning',
  'lunch',
  'dinner',
  'late night',
  'late-night',
  'food',
  'restaurant',
  'beach',
  'surf',
  'work friendly',
  'work-friendly',
];

export function getCuratedVenueSlugsForQuery(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  const shouldLoadSiargao = SIARGAO_QUERY_TOKENS.some((token) => normalized.includes(token));
  return shouldLoadSiargao ? CURATED_SIARGAO_VENUES.map((venue) => venue.slug) : [];
}

export function getCuratedVenueSlugsNear(input: {
  lat: number;
  lng: number;
  radiusMeters: number;
}) {
  const radiusKm = input.radiusMeters / 1000;

  return CURATED_SIARGAO_VENUES
    .filter((venue) => calculateDistance(input.lat, input.lng, venue.latitude, venue.longitude) <= radiusKm)
    .map((venue) => venue.slug);
}

export async function ensureCuratedVenueRecords(slugs: string[]) {
  const uniqueSlugs = Array.from(new Set(slugs)).filter(Boolean);
  if (uniqueSlugs.length === 0) return;

  const selectedVenues = CURATED_SIARGAO_VENUES.filter((venue) => uniqueSlugs.includes(venue.slug));
  if (selectedVenues.length === 0) return;

  await Promise.all(
    selectedVenues.map((venue) =>
      prisma.venue.upsert({
        where: { slug: venue.slug },
        update: {
          name: venue.name,
          description: venue.description,
          address: venue.address,
          city: venue.city,
          country: venue.country,
          latitude: venue.latitude,
          longitude: venue.longitude,
          geohash: encodeGeohash(venue.latitude, venue.longitude, 6),
          timezone: venue.timezone,
          categories: venue.categories,
          placeSource: 'BASEDARE_CURATED',
          externalPlaceId: `curated:${venue.slug}`,
          checkInRadiusMeters: 120,
          metadataJson: {
            curated: true,
            curatedSet: 'siargao-v8',
            locationConfidence: venue.locationConfidence ?? 'externally-checked-anchor',
            coordinatePolicy:
              'Pinned to externally checked venue/map anchors; unresolved venues use explicit approximate land anchors.',
            activationAngle:
              'Food, surf, fitness, wellness, nightlife, and island-discovery missions.',
            ...(venue.instagramHandle ? { instagramHandle: venue.instagramHandle } : {}),
          },
        },
        create: {
          slug: venue.slug,
          name: venue.name,
          description: venue.description,
          address: venue.address,
          city: venue.city,
          country: venue.country,
          latitude: venue.latitude,
          longitude: venue.longitude,
          geohash: encodeGeohash(venue.latitude, venue.longitude, 6),
          timezone: venue.timezone,
          categories: venue.categories,
          placeSource: 'BASEDARE_CURATED',
          externalPlaceId: `curated:${venue.slug}`,
          checkInRadiusMeters: 120,
          metadataJson: {
            curated: true,
            curatedSet: 'siargao-v8',
            locationConfidence: venue.locationConfidence ?? 'externally-checked-anchor',
            coordinatePolicy:
              'Pinned to externally checked venue/map anchors; unresolved venues use explicit approximate land anchors.',
            activationAngle:
              'Food, surf, fitness, wellness, nightlife, and island-discovery missions.',
            ...(venue.instagramHandle ? { instagramHandle: venue.instagramHandle } : {}),
          },
        },
      })
    )
  );
}
